(
b.param['markerNum']=
[
	[25, 23],
	21,
	19,
	[15, 17],
	[15, 16, 17, 18],
	[16, 18],
	20,
	22,
	[26, 24],
	13,
	11,
	9,
	5,
	[5, 6],
	6,
	10,
	12,
	14,
	[1,2,3,4],
	[5, 6],
	[5, 6, 15, 16, 17, 18]
]
);

[
	markerName: ['p1_root', 'p1_hip_L', 'p1_knee_L', 'p1_ankle_L', 'p1_toe_L', 'p1_hip_R', 'p1_knee_R', 'p1_ankle_R', 'p1_toe_R', 'p1_torso', 'p1_neck', 'p1_head', 'p1_shoulder_L', 'p1_elbow_L', 'p1_wrist_L', 'pl_finger_L', 'p1_shoulder_R', 'p1_elbow_R', 'p1_wrist_R', 'pl_finger_R']
]